### ISSUE TITLE
Reminder to change base path when deploying to production

### ISSUE THREAD

**Issue by tecnd** [ABuffSeagull/lazulight-one-year-website#10]
Base paths for both vite and wouter were changed to play nice with GitHub Pages, these should be changed when deploying to production.

**Comment by ABuffSeagull** [comment]
Is it possible to put an environment variable in the action that builds the pages?
That way the `vite.config.ts` can just use `basePath: process.env.VITE_GH_PAGES ? '/lazulight-one-year-website' : '/'` and the `App.tsx` have `Router base={import.meta.env.VITE_GH_PAGES ?  '/lazulight-one-year-website' : '/'}>`
